---
repos:
  # Formatação de código Python com Black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--check"]
        language_version: python3.12.3
  # Qualidade de código Python com Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  # Segurança em Python com Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["--recursive", "."]
        exclude: "^backend/venv/"
  # Qualidade de código React/JS com ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.43.0
    hooks:
      - id: eslint
        args: ["--no-fix"]
  # Validação de arquivos YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
